"""Triage inbox JSON from GCS, score with OpenAI, generate and upload applications."""

from __future__ import annotations

import json
import re
import sys
import tempfile
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import gcs_apps
from app_settings import apply_source_email_to_meta
from openai_tailor import generate_application, score_jd, slugify
from render_assets import render_application_files

_GMAIL_DIR = Path(__file__).resolve().parents[2] / "gmail"
if _GMAIL_DIR.is_dir() and str(_GMAIL_DIR) not in sys.path:
    sys.path.insert(0, str(_GMAIL_DIR))
from text_clean import clean_jd_text  # noqa: E402


def _extract_apply_url(body: str) -> str | None:
    for match in re.finditer(r"https?://[^\s<>\"']+", body):
        url = match.group(0).rstrip(").,]")
        host = urlparse(url).netloc.lower()
        if any(
            x in host
            for x in (
                "greenhouse.io",
                "ashbyhq.com",
                "jobs.ashbyhq.com",
                "linkedin.com/jobs",
                "indeed.com",
                "lever.co",
            )
        ):
            return url
    return None


def _jd_text(msg: dict[str, Any]) -> str:
    body = msg.get("body_text") or msg.get("jd_excerpt") or msg.get("snippet") or ""
    body = clean_jd_text(body)
    subject = msg.get("subject") or ""
    return f"Subject: {subject}\n\n{body}"


def _merge_meta(
    generated: dict[str, Any],
    score_data: dict[str, Any],
    msg: dict[str, Any],
    apply_url: str | None,
) -> dict[str, Any]:
    meta = generated.get("meta_json") or {}
    if not isinstance(meta, dict):
        meta = {}
    today = date.today().isoformat()
    slug_source = score_data.get("slug") or slugify(score_data.get("company") or "company")
    meta.setdefault("company", score_data.get("company"))
    meta.setdefault("client", None)
    meta.setdefault("role", score_data.get("role"))
    meta.setdefault("location", score_data.get("location"))
    meta.setdefault("match_score", score_data.get("match_score"))
    meta.setdefault("status", "ready")
    meta.setdefault("created", today)
    meta.setdefault("updated", today)
    meta.setdefault("salary", score_data.get("salary"))
    meta.setdefault("styling_notes", score_data.get("styling_notes"))
    meta.setdefault("notes", f"Generated by Cloud Run protocols {today}.")
    if apply_url:
        meta.setdefault("apply_url", apply_url)
    meta = apply_source_email_to_meta(meta, msg)
    meta["_slug_hint"] = slug_source
    return meta


def run_triage_generate(*, max_jobs: int = 5) -> dict[str, Any]:
    known = gcs_apps.known_message_ids()
    existing_slugs = gcs_apps.list_application_slugs()
    processed = gcs_apps.load_processed_ids()

    generated_rows: list[dict[str, Any]] = []
    skipped_rows: list[dict[str, Any]] = []
    errors: list[dict[str, Any]] = []

    candidates = gcs_apps.list_inbox_messages()
    candidates.sort(key=lambda m: m.get("date") or "", reverse=True)

    work_count = 0
    for msg in candidates:
        if work_count >= max_jobs:
            break
        mid = msg.get("message_id")
        if not mid or mid in known or mid in processed:
            continue

        body = clean_jd_text(msg.get("body_text") or msg.get("jd_excerpt") or "")
        if len(body.strip()) < 200:
            skipped_rows.append({"message_id": mid, "reason": "body too short for JD"})
            processed.add(mid)
            continue

        apply_url = _extract_apply_url(body)
        jd = _jd_text(msg)

        try:
            score_data = score_jd(jd, subject=msg.get("subject") or "", apply_url=apply_url)
        except Exception as exc:
            errors.append({"message_id": mid, "error": f"score: {exc}"})
            continue

        score = int(score_data.get("match_score") or 0)
        slug = slugify(score_data.get("slug") or score_data.get("company") or "company")
        if slug in existing_slugs:
            skipped_rows.append({"slug": slug, "score": score, "reason": "slug exists"})
            processed.add(mid)
            continue

        if not score_data.get("should_generate"):
            skipped_rows.append(
                {
                    "slug": slug,
                    "score": score,
                    "reason": "below threshold",
                    "gmail_url": msg.get("gmail_url"),
                }
            )
            processed.add(mid)
            continue

        work_count += 1
        try:
            files = generate_application(jd, score_data, apply_url=apply_url)
            meta = _merge_meta(files, score_data, msg, apply_url)
            slug = slugify(meta.pop("_slug_hint", slug))

            jd_txt = files.get("jd_txt") or jd
            resume_html = files.get("resume_html") or ""
            cover_html = files.get("cover_letter_html") or ""
            reply_txt = files.get("reply_email_txt") or ""

            if not resume_html or not cover_html:
                raise RuntimeError("OpenAI returned empty resume or cover letter HTML")

            gcs_apps.upload_application_file(slug, "jd.txt", jd_txt, "text/plain; charset=utf-8")
            gcs_apps.upload_application_file(
                slug,
                "meta.json",
                json.dumps(meta, indent=2) + "\n",
                "application/json",
            )
            gcs_apps.upload_application_file(
                slug, "resume.html", resume_html, "text/html; charset=utf-8"
            )
            gcs_apps.upload_application_file(
                slug, "cover_letter.html", cover_html, "text/html; charset=utf-8"
            )
            if reply_txt:
                gcs_apps.upload_application_file(
                    slug, "reply_email.txt", reply_txt, "text/plain; charset=utf-8"
                )

            with tempfile.TemporaryDirectory() as tmp:
                paths = render_application_files(resume_html, cover_html, Path(tmp))
                for name, path in paths.items():
                    if name.endswith(".html"):
                        continue
                    data = path.read_bytes()
                    ctype = "application/pdf" if name.endswith(".pdf") else (
                        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                    )
                    gcs_apps.upload_application_file(slug, name, data, ctype)

            existing_slugs.add(slug)
            processed.add(mid)
            generated_rows.append(
                {
                    "slug": slug,
                    "score": score,
                    "company": meta.get("company"),
                    "apply_url": meta.get("apply_url") or apply_url,
                    "gmail_url": msg.get("gmail_url"),
                }
            )
        except Exception as exc:
            errors.append({"message_id": mid, "slug": slug, "error": str(exc)})

    gcs_apps.save_processed_ids(processed)
    return {
        "phase": "triage_generate",
        "generated": generated_rows,
        "skipped": skipped_rows,
        "errors": errors,
    }
